import type { Locale } from "../lib/i18n";

const en = {
  title: "Three-AI Development Studio", subtitle: "Live, verifiable development notes with continuous review and an independent final audit.", live: "Live development", loading: "Loading development studio…", emptyTab: "Open a task to view its development studio.",
  lead: "Lead developer", realtime: "Live reviewer", final: "Final auditor", system: "Coordinator", tokens: "Tokens", cost: "Cost", pause: "Pause all three AIs", resume: "Resume all three AIs", paused: "Collaboration paused", running: "All three AIs online", runFinal: "Run final audit", clear: "Clear development events", readOnlyGuard: "Reviewers permanently read-only", budget: "Review budget {tokens} Tokens / turn", views: "Development studio views", timeline: "Learning timeline", findings: "Review findings", finalView: "Final audit", settings: "AI setup", noEvents: "No events in this view yet.", why: "Why:", blocker: "Blocker", high: "High risk", suggestion: "Suggestion", observe: "Observe", teachingMode: "Teaching detail", beginner: "Beginner", engineer: "Engineer", expert: "Expert", enableStudio: "Enable three-AI collaboration", enabled: "Enabled", readOnly: "Permanent read-only access", model: "Model", followModel: "Follow configured model", effort: "Reasoning effort", maxSteps: "Max steps", outputTokens: "Output Tokens", guardrails: "Cost and cadence guardrails", guardrailsHint: "Deduplication, minimum interval, cancellation and per-turn limits stay enforced.", interval: "Minimum review interval (ms)", turnBudget: "Review Token limit / turn", reset: "Undo edits", save: "Save",
};
type Copy = typeof en;
const zh: Copy = { title: "三 AI 开发实况", subtitle: "主开发、实时审查与最终验收全程在线，并提供可验证的开发讲解。", live: "实时开发中", loading: "正在加载开发实况…", emptyTab: "打开一个任务后即可查看开发实况。", lead: "主开发 AI", realtime: "实时审查 AI", final: "最终验收 AI", system: "协作协调器", tokens: "Token", cost: "费用", pause: "暂停三个 AI", resume: "恢复三个 AI", paused: "三 AI 协作已暂停", running: "三个 AI 全程在线", runFinal: "立即执行最终验收", clear: "清空开发记录", readOnlyGuard: "两个审查 AI 永久只读", budget: "本轮审查预算 {tokens} Token", views: "开发实况视图", timeline: "学习时间线", findings: "审查问题", finalView: "最终验收", settings: "AI 配置", noEvents: "这个视图还没有事件。", why: "为什么：", blocker: "阻断", high: "高风险", suggestion: "建议", observe: "观察", teachingMode: "教学详细度", beginner: "入门", engineer: "工程师", expert: "专家", enableStudio: "启用三 AI 协作", enabled: "已启用", readOnly: "永久只读权限", model: "模型", followModel: "跟随已配置模型", effort: "推理强度", maxSteps: "最大步骤", outputTokens: "输出 Token", guardrails: "成本与节奏护栏", guardrailsHint: "始终执行事件去重、最小间隔、取消和单轮预算限制。", interval: "最小审查间隔（毫秒）", turnBudget: "单轮审查 Token 上限", reset: "撤销修改", save: "保存" };
const zhTW: Copy = { ...zh, subtitle: "主開發、即時審查與最終驗收全程在線，並提供可驗證的開發講解。", live: "即時開發中", loading: "正在載入開發實況…", emptyTab: "開啟一個任務後即可查看開發實況。", realtime: "即時審查 AI", system: "協作協調器", pause: "暫停三個 AI", resume: "恢復三個 AI", paused: "三 AI 協作已暫停", clear: "清空開發記錄", readOnlyGuard: "兩個審查 AI 永久唯讀", views: "開發實況視圖", timeline: "學習時間軸", settings: "AI 設定", noEvents: "這個視圖還沒有事件。", why: "為什麼：", high: "高風險", teachingMode: "教學詳細度", enableStudio: "啟用三 AI 協作", readOnly: "永久唯讀權限", followModel: "跟隨已設定模型", effort: "推理強度", maxSteps: "最大步驟", outputTokens: "輸出 Token", guardrails: "成本與節奏護欄", guardrailsHint: "始終執行事件去重、最小間隔、取消和單輪預算限制。", interval: "最小審查間隔（毫秒）", turnBudget: "單輪審查 Token 上限", reset: "復原修改", save: "儲存" };

export function developmentStudioCopy(locale: Locale): Copy { return locale === "zh" ? zh : locale === "zh-TW" ? zhTW : en; }
