import { useEffect, useMemo, useState } from "react";
import { BookOpen, Brain, Check, ChevronRight, Download, FileText, History, Lightbulb, Loader2, Pause, Play, Plus, RotateCcw, Save, Sparkles, Square, Trash2, Upload, Users, WandSparkles, X } from "lucide-react";
import { app } from "../lib/bridge";
import type { NovelAIAction, NovelAIResult, NovelAutoWriteJob, NovelChapter, NovelLongMemory, NovelProject, NovelProjectInput, NovelReviewIssue, NovelVersion } from "../lib/types";
import "./NovelStudioWorkspace.css";

type Props = { onClose: () => void };
const EMPTY_INPUT: NovelProjectInput = { title: "", genre: "悬疑科幻", premise: "", tone: "冷峻、电影感", targetWords: 80000 };

export function NovelStudioWorkspace({ onClose }: Props) {
  const [projects, setProjects] = useState<Array<{ id: string; title: string; genre: string; chapterCount: number; wordCount: number; updatedAt: number }>>([]);
  const [project, setProject] = useState<NovelProject | null>(null);
  const [activeChapterId, setActiveChapterId] = useState("");
  const [tab, setTab] = useState<"write" | "memory" | "auto" | "world" | "characters" | "outline" | "review">("write");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [issues, setIssues] = useState<NovelReviewIssue[]>([]);
  const [versions, setVersions] = useState<NovelVersion[]>([]);
  const [showNew, setShowNew] = useState(false);
  const [newInput, setNewInput] = useState(EMPTY_INPUT);
  const [dirty, setDirty] = useState(false);
  const [memory, setMemory] = useState<NovelLongMemory | null>(null);
  const [jobs, setJobs] = useState<NovelAutoWriteJob[]>([]);
  const [autoTarget, setAutoTarget] = useState(20);
  const [autoWords, setAutoWords] = useState(2500);
  const [autoInstruction, setAutoInstruction] = useState("");

  useEffect(() => { void app.ListNovelProjects().then(setProjects).catch((e) => setMessage(String(e))); }, []);
  useEffect(() => { if (!project && projects[0]) void openProject(projects[0].id); }, [projects]);
  const chapter = useMemo(() => project?.chapters.find((item) => item.id === activeChapterId) || project?.chapters[0], [project, activeChapterId]);
  useEffect(() => { if (chapter && chapter.id !== activeChapterId) setActiveChapterId(chapter.id); }, [chapter, activeChapterId]);
  useEffect(() => { if (!dirty || !chapter) return; const timer = window.setTimeout(() => void saveChapter(), 900); return () => window.clearTimeout(timer); }, [dirty, chapter?.content, chapter?.title]);
  useEffect(() => {
    if (!project) { setMemory(null); setJobs([]); return; }
    let alive = true;
    let previousCompleted = -1;
    const refresh = async () => {
      try {
        const [nextMemory, nextJobs] = await Promise.all([app.NovelMemory(project.id), app.ListNovelAutoWriteJobs(project.id)]);
        if (!alive) return;
        setMemory(nextMemory); setJobs(nextJobs);
        const completed = nextJobs[0]?.completedChapters ?? 0;
        if (previousCompleted >= 0 && completed !== previousCompleted) setProject(await app.LoadNovelProject(project.id));
        previousCompleted = completed;
      } catch (e) { if (alive) setMessage(String(e)); }
    };
    void refresh();
    const timer = window.setInterval(() => void refresh(), 1800);
    return () => { alive = false; window.clearInterval(timer); };
  }, [project?.id]);

  async function openProject(id: string) { setBusy(true); try { const next = await app.LoadNovelProject(id); setProject(next); setIssues([]); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  async function createProject() { setBusy(true); try { const next = await app.CreateNovelProject(newInput); setProject(next); setProjects((old) => [{ id: next.id, title: next.title, genre: next.genre, chapterCount: next.chapters.length, wordCount: next.chapters.reduce((sum, c) => sum + c.wordCount, 0), updatedAt: next.updatedAt }, ...old]); setShowNew(false); setNewInput(EMPTY_INPUT); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  function updateChapter(patch: Partial<NovelChapter>) { if (!project || !chapter) return; setDirty(true); setProject({ ...project, chapters: project.chapters.map((item) => item.id === chapter.id ? { ...item, ...patch } : item) }); }
  async function saveChapter() { if (!project || !chapter) return; try { const saved = await app.SaveNovelChapter(project.id, chapter); setDirty(false); setProject((current) => current ? { ...current, chapters: current.chapters.map((item) => item.id === saved.id ? saved : item), updatedAt: Date.now() } : current); setMessage("已自动保存"); } catch (e) { setMessage(String(e)); } }
  async function saveProject() { if (!project) return; setBusy(true); try { setProject(await app.SaveNovelProject(project)); setMessage("项目设定已保存"); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  async function addChapter() { if (!project) return; const next: NovelChapter = { id: "", title: `第 ${project.chapters.length + 1} 章`, outline: "", content: "", summary: "", status: "draft", order: project.chapters.length + 1, wordCount: 0, updatedAt: Date.now() }; setBusy(true); try { const saved = await app.SaveNovelChapter(project.id, next); setProject({ ...project, chapters: [...project.chapters, saved] }); setActiveChapterId(saved.id); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  async function deleteProject() { if (!project || !window.confirm(`确定删除《${project.title}》及其本地版本吗？`)) return; setBusy(true); try { await app.DeleteNovelProject(project.id); const remaining = projects.filter((item) => item.id !== project.id); setProjects(remaining); setProject(null); if (remaining[0]) await openProject(remaining[0].id); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  function addCharacter() { if (!project) return; setProject({ ...project, characters: [...project.characters, { id: `character-${Date.now()}`, name: "新人物", role: "配角", traits: "", arc: "", notes: "" }] }); }
  function updateCharacter(id: string, patch: Partial<NovelProject["characters"][number]>) { if (!project) return; setProject({ ...project, characters: project.characters.map((item) => item.id === id ? { ...item, ...patch } : item) }); }
  async function restoreVersion(versionId: string) { if (!project || !chapter) return; setBusy(true); try { const restored = await app.RestoreNovelVersion(project.id, chapter.id, versionId); setProject({ ...project, chapters: project.chapters.map((item) => item.id === restored.id ? restored : item) }); setMessage("已恢复历史版本"); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  async function ai(action: NovelAIAction) { if (!project) return; setBusy(true); setMessage(""); try { let activeChapter = chapter; if (activeChapter && dirty) { activeChapter = await app.SaveNovelChapter(project.id, activeChapter); setDirty(false); } const result: NovelAIResult = await app.GenerateNovelContent({ projectId: project.id, chapterId: activeChapter?.id, action }); if (result.content && activeChapter) { const generated = { ...activeChapter, content: action === "continue" ? `${activeChapter.content}\n\n${result.content}` : result.content, summary: result.summary || activeChapter.summary, status: "review" as const }; const saved = await app.SaveNovelChapter(project.id, generated); setProject({ ...project, chapters: project.chapters.map((item) => item.id === saved.id ? saved : item) }); setDirty(false); const reviews = await Promise.all([app.GenerateNovelContent({ projectId: project.id, chapterId: saved.id, action: "review-live" }), app.GenerateNovelContent({ projectId: project.id, chapterId: saved.id, action: "review-final" })]); setIssues(reviews.flatMap((item) => item.issues || [])); } if (result.issues) { setIssues(result.issues); setTab("review"); } if (result.outlines?.length) { const saved = await app.SaveNovelProject({ ...project, outlines: result.outlines }); setProject(saved); } setMessage(action.startsWith("review") ? "审查完成" : "三位 AI 已完成创作与双重审查"); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  async function exportProject(format: string) { if (!project) return; setBusy(true); try { const result = await app.ExportNovelProject(project.id, format); const path = await app.PickExportFile(result.filename, result.mime); if (path) await app.SaveExportFile(path, result.payload, result.base64Encoded); setMessage("已导出作品"); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  async function loadVersions() { if (!project || !chapter) return; try { setVersions(await app.ListNovelVersions(project.id, chapter.id)); } catch (e) { setMessage(String(e)); } }
  async function importBible() { if (!project) return; setBusy(true); setMessage(""); try { const result = await app.ImportNovelBible(project.id); setMemory(result.memory); setMessage(`已导入 ${result.bible.filename}，长记忆已建立`); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  async function startAutoWrite() { if (!project) return; setBusy(true); setMessage(""); try { const created = await app.StartNovelAutoWrite({ projectId: project.id, targetChapters: autoTarget, targetWordsPerChapter: autoWords, instruction: autoInstruction }); setJobs((current) => [created, ...current]); setMessage("连续创作已启动，可关闭工作室让它在后台继续"); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  async function controlJob(action: "pause" | "resume" | "stop", id: string) { try { if (action === "pause") await app.PauseNovelAutoWrite(id); else if (action === "resume") await app.ResumeNovelAutoWrite(id); else await app.StopNovelAutoWrite(id); setJobs(await app.ListNovelAutoWriteJobs(project?.id || "")); } catch (e) { setMessage(String(e)); } }

  return <section className="novel-studio" aria-label="AI 小说工作室">
    <header className="novel-studio__header"><div className="novel-studio__brand"><span className="novel-studio__logo"><BookOpen size={21} /></span><div><span>REASONIX NOVEL STUDIO</span><h1>AI 小说工作室</h1></div></div><div className="novel-studio__header-actions"><button type="button" onClick={() => setShowNew(true)}><Plus size={15} />新建项目</button><button type="button" onClick={() => void saveProject()} disabled={!project}><Save size={15} />保存设定</button><label className="novel-export"><Download size={15} /><select defaultValue="" disabled={!project || busy} onChange={(e) => { if (e.target.value) void exportProject(e.target.value); e.target.value = ""; }}><option value="" disabled>导出</option><option value="md">Markdown</option><option value="txt">TXT</option><option value="docx">Word DOCX</option></select></label><button type="button" title="删除项目" onClick={() => void deleteProject()} disabled={!project}><Trash2 size={15} /></button><button className="novel-studio__close" type="button" onClick={onClose}><X size={18} /></button></div></header>
    <div className="novel-studio__body">
      <aside className="novel-studio__projects"><div className="novel-studio__aside-title">我的小说 <span>{projects.length}</span></div>{projects.map((item) => <button type="button" key={item.id} className={project?.id === item.id ? "is-active" : ""} onClick={() => void openProject(item.id)}><BookOpen size={15} /><span><strong>{item.title}</strong><small>{item.genre} · {item.chapterCount} 章</small></span><ChevronRight size={14} /></button>)}</aside>
      {project ? <main className="novel-studio__main"><div className="novel-studio__project-bar"><div><span className="novel-studio__eyebrow">{project.genre} · {project.tone}</span><h2>{project.title}</h2><p>{project.premise || "给你的故事一个清晰的起点。"}</p></div><div className="novel-studio__stats"><strong>{project.chapters.reduce((sum, c) => sum + c.wordCount, 0).toLocaleString()}</strong><small>总字数</small><strong>{project.chapters.length}</strong><small>章节</small></div></div>
        <nav className="novel-studio__tabs"><button className={tab === "write" ? "is-active" : ""} onClick={() => setTab("write")}><FileText size={15} />章节写作</button><button className={tab === "auto" ? "is-active" : ""} onClick={() => setTab("auto")}><Play size={15} />连续创作{jobs.some((item) => item.status === "running") && <b className="is-running">运行中</b>}</button><button className={tab === "memory" ? "is-active" : ""} onClick={() => setTab("memory")}><Brain size={15} />作品圣经</button><button className={tab === "world" ? "is-active" : ""} onClick={() => setTab("world")}><Lightbulb size={15} />世界观</button><button className={tab === "characters" ? "is-active" : ""} onClick={() => setTab("characters")}><Users size={15} />人物卡</button><button className={tab === "outline" ? "is-active" : ""} onClick={() => setTab("outline")}><Sparkles size={15} />故事大纲</button><button className={tab === "review" ? "is-active" : ""} onClick={() => setTab("review")}><Check size={15} />审查结果{issues.length > 0 && <b>{issues.length}</b>}</button></nav>
        {tab === "write" && <div className="novel-writing"><aside className="novel-writing__chapters"><div className="novel-studio__aside-title">章节 <button type="button" onClick={() => void addChapter()} title="新增章节"><Plus size={13} /></button></div>{project.chapters.map((item) => <button type="button" key={item.id} className={chapter?.id === item.id ? "is-active" : ""} onClick={() => setActiveChapterId(item.id)}><span>{String(item.order).padStart(2, "0")}</span><strong>{item.title}</strong><small>{item.wordCount} 字</small></button>)}</aside>{chapter ? <><section className="novel-editor"><div className="novel-editor__toolbar"><input value={chapter.title} onChange={(e) => updateChapter({ title: e.target.value })} aria-label="章节标题" /><span>{chapter.status === "review" ? "待审查" : "草稿"}</span><button type="button" onClick={() => void saveChapter()} disabled={busy}><Save size={14} />保存</button></div><textarea value={chapter.content} onChange={(e) => updateChapter({ content: e.target.value })} placeholder="从一个有张力的画面开始..." /><div className="novel-editor__footer"><span>{chapter.content.length.toLocaleString()} 字 · 自动保存到本地</span><div><button type="button" onClick={() => void ai("continue")} disabled={busy}><WandSparkles size={14} />续写</button><button type="button" onClick={() => void ai("expand")} disabled={busy}>扩写</button><button type="button" onClick={() => void ai("polish")} disabled={busy}>润色</button></div></div></section><aside className="novel-ai-rail"><div className="novel-ai-rail__title"><span>三 AI 协作</span><small>实时辅助</small></div><div className="novel-ai-card novel-ai-card--main"><span className="novel-ai-card__dot" /><div><strong>主 AI · Novelist</strong><p>负责构思、续写与语言表达</p></div><button type="button" onClick={() => void ai("draft")} disabled={busy}>创作</button></div><div className="novel-ai-card"><span className="novel-ai-card__dot" /><div><strong>审查 AI · Continuity</strong><p>检查逻辑、人物一致性和节奏</p></div><button type="button" onClick={() => void ai("review-live")} disabled={busy}>检查</button></div><div className="novel-ai-card"><span className="novel-ai-card__dot" /><div><strong>完稿 AI · Editor</strong><p>章节完成后给出出版级建议</p></div><button type="button" onClick={() => void ai("review-final")} disabled={busy}>审阅</button></div><div className="novel-ai-rail__tip"><Sparkles size={14} /><span>写作建议会基于世界观、人物卡和最近章节摘要生成，减少上下文消耗。</span></div></aside></> : <div className="novel-empty"><h2>还没有章节</h2><button type="button" onClick={() => void addChapter()}><Plus size={14} />创建第一章</button></div>}</div>}
        {tab === "auto" && <NovelAutoPanel project={project} jobs={jobs} target={autoTarget} words={autoWords} instruction={autoInstruction} busy={busy} onTarget={setAutoTarget} onWords={setAutoWords} onInstruction={setAutoInstruction} onStart={() => void startAutoWrite()} onControl={(action, id) => void controlJob(action, id)} />}
        {tab === "memory" && <NovelMemoryPanel memory={memory} busy={busy} onImport={() => void importBible()} />}
        {tab === "world" && <div className="novel-settings-grid"><Setting label="时代与背景" value={project.world.era} onChange={(value) => setProject({ ...project, world: { ...project.world, era: value } })} /><Setting label="地点与空间" value={project.world.locations} onChange={(value) => setProject({ ...project, world: { ...project.world, locations: value } })} /><Setting label="世界运行规则" value={project.world.rules} onChange={(value) => setProject({ ...project, world: { ...project.world, rules: value } })} /><Setting label="主题与意象" value={project.world.themes} onChange={(value) => setProject({ ...project, world: { ...project.world, themes: value } })} /></div>}
        {tab === "characters" && <div className="novel-character-grid">{project.characters.map((item) => <article key={item.id}><div className="novel-character-grid__avatar">{item.name.slice(0, 1)}</div><input value={item.name} onChange={(e) => updateCharacter(item.id, { name: e.target.value })} aria-label="人物名称" /><input value={item.role} onChange={(e) => updateCharacter(item.id, { role: e.target.value })} aria-label="人物角色" /><textarea value={item.traits} onChange={(e) => updateCharacter(item.id, { traits: e.target.value })} placeholder="性格、外貌与声音" /><input value={item.arc} onChange={(e) => updateCharacter(item.id, { arc: e.target.value })} placeholder="人物弧光" /></article>)}<button type="button" className="novel-add-card" onClick={addCharacter}><Plus size={19} />添加人物卡</button></div>}
        {tab === "outline" && <div className="novel-outline"><div className="novel-outline__head"><div><span>STORY ARCHITECT</span><h3>让主 AI 规划你的长篇结构</h3></div><button type="button" onClick={() => void ai("outline")} disabled={busy}><Sparkles size={14} />生成大纲</button></div>{project.outlines.length ? project.outlines.map((item, index) => <div className="novel-outline__item" key={item.id}><b>{String(index + 1).padStart(2, "0")}</b><div><strong>{item.title}</strong><p>{item.summary}</p></div></div>) : <div className="novel-empty">还没有大纲，先让主 AI 帮你建立故事骨架。</div>}</div>}
        {tab === "review" && <div className="novel-review"><div className="novel-review__head"><div><span>EDITORIAL REVIEW</span><h3>{issues.length ? `发现 ${issues.length} 个可优化点` : "章节审查中心"}</h3></div><button type="button" onClick={() => void ai("review-final")} disabled={busy}><Check size={14} />运行完稿审查</button></div>{issues.length ? issues.map((issue, index) => <article key={`${issue.title}-${index}`} className={`novel-issue novel-issue--${issue.severity}`}><span>{issue.severity === "critical" ? "严重" : issue.severity === "warning" ? "建议" : "提示"}</span><div><strong>{issue.title}</strong><small>{issue.category}</small><p>{issue.detail}</p><em>建议：{issue.suggestion}</em></div></article>) : <div className="novel-empty">完成一段正文后运行实时审查，主 AI 会继续保持创作节奏。</div>}<div className="novel-history"><div><History size={15} />版本历史</div><button type="button" onClick={() => void loadVersions()}>加载当前章节版本</button>{versions.map((version) => <button type="button" key={version.id} onClick={() => void restoreVersion(version.id)}>{version.label} · {version.wordCount} 字</button>)}</div></div>}
      </main> : <div className="novel-empty novel-empty--full"><BookOpen size={30} /><h2>开始一部新小说</h2><p>创建项目后，世界观、人物、章节和三 AI 协作都会在这里展开。</p><button type="button" onClick={() => setShowNew(true)}><Plus size={15} />创建项目</button></div>}
    </div>
    {busy && <div className="novel-studio__busy"><Loader2 size={16} className="spin" />AI 正在处理...</div>}{message && <div className="novel-studio__toast">{message}</div>}
    {showNew && <div className="novel-modal-backdrop"><div className="novel-modal"><div className="novel-modal__head"><div><span>NEW PROJECT</span><h2>创建小说项目</h2></div><button type="button" onClick={() => setShowNew(false)}><X size={17} /></button></div><label>作品名称<input autoFocus value={newInput.title} onChange={(e) => setNewInput({ ...newInput, title: e.target.value })} placeholder="例如：雾港来信" /></label><label>类型<input value={newInput.genre} onChange={(e) => setNewInput({ ...newInput, genre: e.target.value })} /></label><label>一句话梗概<textarea value={newInput.premise} onChange={(e) => setNewInput({ ...newInput, premise: e.target.value })} placeholder="主角、目标与阻力是什么？" /></label><div className="novel-modal__actions"><button type="button" onClick={() => setShowNew(false)}>取消</button><button type="button" className="primary" onClick={() => void createProject()} disabled={!newInput.title.trim() || busy}><Plus size={15} />创建并开始</button></div></div></div>}
  </section>;
}

function NovelAutoPanel({ project, jobs, target, words, instruction, busy, onTarget, onWords, onInstruction, onStart, onControl }: { project: NovelProject; jobs: NovelAutoWriteJob[]; target: number; words: number; instruction: string; busy: boolean; onTarget: (value: number) => void; onWords: (value: number) => void; onInstruction: (value: string) => void; onStart: () => void; onControl: (action: "pause" | "resume" | "stop", id: string) => void }) {
  const active = jobs.find((item) => ["queued", "running", "paused", "failed"].includes(item.status));
  const progress = active ? Math.min(100, Math.round((active.completedChapters / Math.max(1, active.targetChapters)) * 100)) : 0;
  return <div className="novel-auto">
    <section className="novel-auto__hero"><div><span>AUTONOMOUS SERIAL WRITING</span><h3>让故事自己向前生长</h3><p>主笔、连续性编辑与完稿编辑按章协作。每章完成即保存并更新长记忆，你可以随时暂停或停止。</p></div><div className="novel-auto__engine"><i /><span>后台创作引擎</span><strong>{active?.status === "running" ? "运行中" : active?.status === "paused" ? "已暂停" : "待命"}</strong></div></section>
    {active ? <section className="novel-auto__active"><div className="novel-auto__progress-head"><div><small>{active.phase}</small><strong>{active.currentChapterTitle || "正在准备下一章"}</strong></div><b>{progress}%</b></div><div className="novel-auto__progress"><span style={{ width: `${progress}%` }} /></div><div className="novel-auto__metrics"><span><b>{active.completedChapters}</b> 已完成</span><span><b>{active.targetChapters}</b> 目标章节</span><span><b>{active.targetWordsPerChapter}</b> 单章目标字数</span></div>{active.lastError && <p className="novel-auto__error">{active.lastError}</p>}<div className="novel-auto__controls">{active.status === "running" || active.status === "queued" ? <button type="button" onClick={() => onControl("pause", active.id)}><Pause size={15} />暂停</button> : <button type="button" onClick={() => onControl("resume", active.id)}><RotateCcw size={15} />继续</button>}<button type="button" className="danger" onClick={() => onControl("stop", active.id)}><Square size={14} />停止任务</button></div></section> : <section className="novel-auto__setup"><div className="novel-auto__fields"><label>写到第几章<input type="number" min={project.chapters.length + 1} max={1000} value={target} onChange={(e) => onTarget(Number(e.target.value))} /></label><label>每章目标字数<input type="number" min={500} max={20000} step={100} value={words} onChange={(e) => onWords(Number(e.target.value))} /></label></div><label>连续创作要求<textarea value={instruction} onChange={(e) => onInstruction(e.target.value)} placeholder="例如：保持慢热悬疑节奏，每三章回收一个伏笔，不要过早揭示幕后人物。" /></label><div className="novel-auto__launch"><div><strong>从第 {project.chapters.length + 1} 章开始</strong><small>关闭工作室后仍会在桌面后台继续；退出应用后，下次启动会从章节检查点恢复。</small></div><button type="button" onClick={onStart} disabled={busy || target <= project.chapters.length}><Play size={16} />开始连续创作</button></div></section>}
    {jobs.length > 0 && <section className="novel-auto__history"><h4>任务记录</h4>{jobs.slice(0, 6).map((job) => <div key={job.id}><span className={`status status--${job.status}`} /> <strong>{job.phase}</strong><small>{job.completedChapters}/{job.targetChapters} 章 · {new Date(job.updatedAt).toLocaleString()}</small></div>)}</section>}
  </div>;
}

function NovelMemoryPanel({ memory, busy, onImport }: { memory: NovelLongMemory | null; busy: boolean; onImport: () => void }) {
  const hasBible = Boolean(memory?.bible?.filename);
  return <div className="novel-memory"><section className="novel-memory__import"><div className="novel-memory__icon"><Brain size={28} /></div><div><span>LONG-TERM STORY MEMORY</span><h3>{hasBible ? memory?.bible.filename : "上传作品圣经，建立故事的长期记忆"}</h3><p>{hasBible ? `${memory?.bible.characters.toLocaleString()} 字符 · 已提取世界规则、人物状态、时间线和创作约束` : "支持 Markdown、TXT 和 DOCX。原文件保存在本地；点击导入并分析后，内容会发送给当前配置的模型供应商进行结构化提取。"}</p></div><button type="button" onClick={onImport} disabled={busy}><Upload size={16} />{hasBible ? "重新导入" : "导入并分析"}</button></section>
    {hasBible ? <div className="novel-memory__grid"><article className="novel-memory__summary"><span>全局故事摘要</span><p>{memory?.globalSummary || memory?.bible.summary}</p><em>{memory?.bible.style}</em></article><MemoryList title="时间线" items={memory?.timeline || []} /><MemoryList title="确定事实" items={memory?.facts || []} /><MemoryList title="未回收伏笔" items={memory?.openThreads || []} /><MemoryList title="不可违背约束" items={memory?.constraints || []} /><article><span>人物最新状态</span>{Object.entries(memory?.characterStates || {}).slice(0, 12).map(([name, state]) => <p key={name}><strong>{name}</strong>{state}</p>)}</article></div> : <div className="novel-memory__empty"><FileText size={26} /><strong>还没有作品圣经</strong><span>导入后，连续创作不会只依赖最近几章，而会持续维护可检索的故事事实。</span></div>}
  </div>;
}

function MemoryList({ title, items }: { title: string; items: string[] }) { return <article><span>{title}</span>{items.slice(0, 12).map((item, index) => <p key={`${title}-${index}`}>{item}</p>)}{items.length === 0 && <small>暂无记录</small>}</article>; }

function Setting({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="novel-setting"><span>{label}</span><textarea value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
